library(HIVepisim)
library(ape)
library(skygrowth)
library(stringr)

#function to get tree and convert branch lengths from days to years
convert_branches <- function(tree, scale = 1/365){

  #convert branch lenghts from days to years ----
  tree$edge.length <- tree$edge.length * 1/365

  if(!is.null(tree$root.edge)){
    tree$root.edge <- tree$root.edge * 1/365
  }

  return(tree)
}



# get tip names
sim <- readRDS("Analyses/sim_for_tests.RDS")

tm <- get_transmat(sim)
transphylo <- toPhylo_transmatOrigin(tm,
                                     format = "migrant",
                                     by_areas = "all",
                                     max_value = NULL,
                                     tips_only = TRUE)





# read trees generated by VirusTreeSimulator
# working directory
wd <- "Analyses/Results/VirusTreeSimulator_trees"
#input_files <- "~/Box Sync/my_R_packages/pangea/Analyses/Alignments/South_Africa/byCodon/drug_resistance/phylip_alignment"


# List all files that contain ".phy" in "input_files"
ali_files <- as.matrix(Sys.glob(file.path(wd, "*_simple.nex")))


#Read VirusTreeSimulator tree
vts_tree <- read.nexus(ali_files[1])

# convert branch lengths from days to years
tree_years <- convert_branches(tree = vts_tree, scale = 1/365)

# Get tip names in the form of ID_migrant
tip_names_migrant <- transphylo$seed_395$tip.label
tip_names_migrant_ID <- str_match(string = tip_names_migrant, pattern = "\\d+")
#get tip names from VirusTreeSimulato tree
tip_names <- tree_years$tip.label
tip_names_ID <- str_match(string = tip_names, pattern = "\\d+")

# reorder ID names
# Saving indices for how to reorder `tip_names_migrant_ID` to match `tip_names_ID`
reorder_idx <- match(tip_names_ID, tip_names_migrant_ID)

# Reordering the tip_names_migrant_ID  to match the order of the tip_names_ID vector
reordered_tip_names <- tip_names_migrant[reorder_idx]

# change the tips names returned by VirusTreeSimulator to those tip_names
# in the form of ID_migrant
tree_years$tip.label <- reordered_tip_names


# save tree to simulate sequence alignment using Python script
write.tree(phy = tree_years, file = "seed_395_vts_years.tre")




## skygrowth ----

# remove all sequences
all_matches <- str_match_all(string = tree_years$tip.label, pattern = "(\\d+_)(\\d+)")
mig_code <- unlist(lapply(all_matches, function(x) x[3]))

# drop tips that are not from region
toKeep <- tree_years$tip.label[ grepl(pattern='_1$', x = tree_years$tip.label)]
toDrop <- setdiff(tree_years$tip.label, toKeep)

tr2 <- drop.tip(tree_years, toDrop)





mcmcfit <- skygrowth.mcmc(tr2)
mcmcfit$time <- mcmcfit$time + 2018
plot(mcmcfit, logy=FALSE)
